[package]
name = "b-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.18.0"
bevy_pipelines_ready = "0.8.0"
quinn = "0.11.9"

[[test]]
name = "tests"
path = "tests/simple.rs"
harness = false
